version: '3.8'

services:
  cancellations-sop:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./processed_reports:/app/processed_reports
      - ./.env:/app/.env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  cancellations-sop-dev:
    build: .
    ports:
      - "8502:8501"
    volumes:
      - ./src:/app/src
      - ./processed_reports:/app/processed_reports
      - ./.env:/app/.env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
    command: ["streamlit", "run", "src/app/main.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
    profiles:
      - dev
